apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: stream
  namespace: processing
spec:
  version: 3.6.0
  replicas: 1
  bootstrapServers: stream-kafka-bootstrap:9092
  config:
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 3Gi
      cpu: 1000m
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - etl-dev-worker
