apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-mysql-api
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-mysql-api
            image: fabianofpena/ingestion-app:1.3
            imagePullPolicy: IfNotPresent
            command: ["python3", "run.py", "100"]
            env:
            - name: DB_DIALECT
              value: "mysql+mysqlconnector"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "HOxuRQgt38=$"
            - name: DB_HOST
              value: "mysql.database.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "retail"
          restartPolicy: OnFailure
